### PR TITLE
Re-enable UI when running on k8s

### PR DESCRIPTION
**Pull request by fbladilo**
Remove force-disablement of UI on k8s clusters as work on this will be starting during this Forklift release.

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
Why not wait until we have a solution in place for the UI authentication? Until then, re-enabling the UI will make the deployment fail.

**Comment by fbladilo** [comment]
@fdupont-redhat the deployment of UI actually succeeds , the issue is that UI does not know yet how to handle the absence of oauth2 , we can wait or just have it available for UI devs so they can successfully begin their testing with latest operator.

**Comment by fdupont-redhat** [comment]
But they can already enable the UI with `feature_ui: true`, no?

**Comment by fbladilo** [comment]
@fdupont-redhat They can set feature_ui: true and will take precedence but the controlling variable in that conditional is k8s_cluster meaning that only gets processed on OpenShift and not k8s , they will have to force that variable too but will have unintended consequences.

**Review by fdupont-redhat — APPROVED** [review]
Thanks for the explanation.

**Pull request merged**
