### PR TITLE
Increased CPU limit; Add subdirectory to profiler path.

### PR DESCRIPTION
**Pull request by jortel**
Increased CPU limit based on scale testing.  300m may not be enough but much better than 100m.
Only really needed by the inventory container but don't think the _main_ controller container will ever actually use it.

Each container needs to write to a separate directory else the profiler in both containers write (overwrite) the same file.

**Note**: I HAVE NOT TESTED the changes but thought the PR would be the easiest way to describe the requested changes.

### CODE REVIEW

**Comment by fbladilo** [comment]
LGTM , tested forklift latest on OCP 4.7 using proper CR for changes :

**Review by fbladilo — APPROVED** [review]
LGTM

**Comment by dgur** [comment]
Can you suggest how QE can validate  it? @jortel

**Comment by fdupont-redhat** [comment]
There's nothing to validate here. It's a technical parameter that changes.
The best you can do is confirm that the controller container CPU limit is now "500m".

**Pull request merged**
